In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,roc_curve,accuracy_score,mean_absolute_error
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings('ignore')



In [26]:
df=pd.read_csv('Admission_Predict_Ver1.1.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [4]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         500 non-null    int64  
 1   GRE Score          500 non-null    int64  
 2   TOEFL Score        500 non-null    int64  
 3   University Rating  500 non-null    int64  
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64  
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB


In [27]:
df.drop('Serial No.',axis=1,inplace=True)

In [20]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [21]:
df['Chance of Admit ']

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit , Length: 500, dtype: float64

In [28]:
x=df.drop('Chance of Admit ',axis=1)
y=df['Chance of Admit ']

In [24]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
495        332          108                  5  4.5   4.0  9.02         1
496        337          117                  5  5.0   5.0  9.87         1
497        330          120                  5  4.5   5.0  9.56         1
498        312          103                  4  4.0   5.0  8.43         0
499        327          113                  4  4.5   4.5  9.04         0

[500 rows x 7 columns]

In [29]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
495        332          108                  5  4.5   4.0  9.02         1
496        337          117                  5  5.0   5.0  9.87         1
497        330          120                  5  4.5   5.0  9.56         1
498        312          103                  4  4.0   5.0  8.43         0
499        327          113                  4  4.5   4.5  9.04         0

[500 rows x 7 columns]

In [30]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit , Length: 500, dtype: float64

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2)

In [32]:
knn_model=KNeighborsRegressor()
knn_model.fit(x_train,y_train)

KNeighborsRegressor()

In [35]:
# for testing data 

y_pred = knn_model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)
print('mse is :',mse)

mae=mean_absolute_error(y_test,y_pred)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_test,y_pred)
print('R2 is :',R2)


mse is : 0.005351159999999998
mae is : 0.05553999999999999
rmse is : 0.07315162335861042
R2 is : 0.7228957588938948


In [34]:
# for training  data 

y_pred_train = knn_model.predict(x_train)

mse=mean_squared_error(y_train,y_pred_train)
print('mse is :',mse)

mae=mean_absolute_error(y_train,y_pred_train)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_train,y_pred_train)
print('R2 is :',R2)

mse is : 0.0037576299999999997
mae is : 0.045845000000000004
rmse is : 0.06129951060163531
R2 is : 0.8123052035333229


In [37]:
linear_model=LinearRegression()
linear_model.fit(x_train,y_train)

LinearRegression()

In [38]:
# for testing data 

y_pred = linear_model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)
print('mse is :',mse)

mae=mean_absolute_error(y_test,y_pred)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_test,y_pred)
print('R2 is :',R2)

mse is : 0.0034590988971363807
mae is : 0.04020019380415797
rmse is : 0.058814104576507674
R2 is : 0.8208741703103734


In [39]:
# for training  data 

y_pred_train = linear_model.predict(x_train)

mse=mean_squared_error(y_train,y_pred_train)
print('mse is :',mse)

mae=mean_absolute_error(y_train,y_pred_train)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_train,y_pred_train)
print('R2 is :',R2)

mse is : 0.0035733525638779674
mae is : 0.04294488315548092
rmse is : 0.05977752557506849
R2 is : 0.8215099192361265


# standardisation 

In [40]:
scaler= StandardScaler()
x_scaled=scaler.fit_transform(x_train)
x_scaled

array([[-0.53736015, -0.51949116, -0.05463584, ...,  0.00933125,
        -0.32658176, -1.11114215],
       [ 0.16363964,  0.44925692, -1.8029826 , ...,  0.00933125,
        -0.04593523,  0.89997486],
       [-1.41360989, -1.0038652 , -0.05463584, ..., -1.05709751,
        -1.13550409, -1.11114215],
       ...,
       [ 0.77701445, -0.03511712, -0.05463584, ...,  0.00933125,
         0.89505605,  0.89997486],
       [ 0.86463943,  0.61071493,  1.69371093, ...,  0.54254563,
         1.09315948,  0.89997486],
       [-1.41360989, -0.35803314, -1.8029826 , ..., -1.59031189,
        -1.26757304, -1.11114215]])

In [42]:
x_test_scaled=scaler.transform(x_test)
x_test_scaled

array([[-0.27448523, -0.19657513, -0.92880922, -0.84504549, -1.59031189,
        -0.22753004, -1.11114215],
       [-0.3621102 , -0.03511712, -0.05463584, -0.3523076 , -0.52388313,
        -0.17800418,  0.89997486],
       [ 2.00376408,  1.90237904,  1.69371093,  1.1259061 ,  0.54254563,
         1.86906457, -1.11114215],
       [-0.01161031, -0.03511712, -0.92880922,  0.1404303 ,  0.00933125,
         0.11915096,  0.89997486],
       [ 0.77701445,  0.44925692,  0.81953755,  1.1259061 ,  0.54254563,
         0.64742677,  0.89997486],
       [-0.44973518, -1.0038652 , -0.92880922, -0.84504549,  0.00933125,
        -0.37610761,  0.89997486],
       [ 0.33888959, -0.51949116, -0.05463584, -0.3523076 ,  0.00933125,
         0.28423715,  0.89997486],
       [ 0.9522644 , -0.68094917, -0.05463584,  0.6331682 ,  0.54254563,
        -0.44214209,  0.89997486],
       [ 0.42651456,  0.61071493, -0.05463584,  0.1404303 ,  0.54254563,
         0.43281472,  0.89997486],
       [ 0.16363964, -0.1965

In [44]:
knn_model.fit(x_scaled,y_train)

KNeighborsRegressor()

In [45]:
# for training  data 

y_pred_train = knn_model.predict(x_scaled)

mse=mean_squared_error(y_train,y_pred_train)
print('mse is :',mse)

mae=mean_absolute_error(y_train,y_pred_train)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_train,y_pred_train)
print('R2 is :',R2)

mse is : 0.0028745100000000003
mae is : 0.038885
rmse is : 0.05361445700555029
R2 is : 0.8564173243796147


In [46]:
# for testing data 

y_pred = knn_model.predict(x_test_scaled)

mse=mean_squared_error(y_test,y_pred)
print('mse is :',mse)

mae=mean_absolute_error(y_test,y_pred)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_test,y_pred)
print('R2 is :',R2)

mse is : 0.0042350800000000004
mae is : 0.04534
rmse is : 0.06507749226883286
R2 is : 0.7806907979907824


In [47]:
linear_model.fit(x_scaled,y_train)

LinearRegression()

In [48]:
# for training  data 

y_pred_train = linear_model.predict(x_scaled)

mse=mean_squared_error(y_train,y_pred_train)
print('mse is :',mse)

mae=mean_absolute_error(y_train,y_pred_train)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_train,y_pred_train)
print('R2 is :',R2)

mse is : 0.0035733525638779674
mae is : 0.04294488315548091
rmse is : 0.05977752557506849
R2 is : 0.8215099192361265


In [49]:
# for testing data 

y_pred = linear_model.predict(x_test_scaled)

mse=mean_squared_error(y_test,y_pred)
print('mse is :',mse)

mae=mean_absolute_error(y_test,y_pred)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_test,y_pred)
print('R2 is :',R2)

mse is : 0.003459098897136384
mae is : 0.040200193804157944
rmse is : 0.0588141045765077
R2 is : 0.8208741703103731


# Hyperparameter 

In [50]:
hyperparam = {'n_neighbors':np.arange(3,30),'p':[1,2]}
gscv_model=GridSearchCV(knn_model,hyperparam,cv=5)
gscv_model.fit(x_scaled,y_train)
gscv_model.best_estimator_

KNeighborsRegressor(n_neighbors=29)

In [51]:
knn_model=KNeighborsRegressor(n_neighbors=29)
knn_model.fit(x_scaled,y_train)

KNeighborsRegressor(n_neighbors=29)

In [52]:
# for training  data 

y_pred_train = knn_model.predict(x_scaled)

mse=mean_squared_error(y_train,y_pred_train)
print('mse is :',mse)

mae=mean_absolute_error(y_train,y_pred_train)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_train,y_pred_train)
print('R2 is :',R2)

mse is : 0.004080166765755054
mae is : 0.04576465517241379
rmse is : 0.0638761830869304
R2 is : 0.7961943909729018


In [53]:
# for testing data 

y_pred = knn_model.predict(x_test_scaled)

mse=mean_squared_error(y_test,y_pred)
print('mse is :',mse)

mae=mean_absolute_error(y_test,y_pred)
print('mae is :',mae)

rmse=np.sqrt(mse)
print('rmse is :',rmse)

R2 =r2_score(y_test,y_pred)
print('R2 is :',R2)

mse is : 0.003985324613555291
mae is : 0.043937931034482756
rmse is : 0.06312942747685338
R2 is : 0.7936241202653778


# single row data test

In [56]:
df.head(1)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   

   Chance of Admit   
0              0.92

In [57]:
GRE_Score=337.00
TOEFL_Score=118.00
University_Rating=4.00
SOP=4.50
LOR=4.50
CGPA=9.65
Research=1.00

In [59]:
test_array=np.array([GRE_Score,TOEFL_Score,University_Rating,SOP,LOR,CGPA,Research])
test_array

array([337.  , 118.  ,   4.  ,   4.5 ,   4.5 ,   9.65,   1.  ])

In [64]:
result=scaler.transform([test_array])

In [65]:
linear_model.predict(result)[0]

0.9523095338956548

In [66]:
import pickle

In [67]:
with open ('linear_model.pkl','wb')as f :
    pickle.dump(linear_model,f)

In [68]:
with open ('std_scaler.pkl','wb')as f :
    pickle.dump(scaler,f)